NOISSUE - Add version filter
mainflux/callhome pull request #21
Opened 2023-08-02 20:49 UTC by 1998-felix

### What does this do?
Add version filter to callhome sdk

### Which issue(s) does this PR fix/relate to?
Resolves ultravioletrs/issues#270

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No
### Notes

2023-08-02 20:50 UTC, drasko commented
@SammyOina please review

2023-08-03 07:20 UTC, ianmuchyri commented
@1998-felix  this PR has commits that have already been merged in the main branch I can see` Add city filter` and `Fix missing country in OpenAPI` have already been merged in the main branch. Check on that

2023-08-03 08:37 UTC, ianmuchyri approved these changes

2023-08-03 09:24 UTC, SammyOina requested changes

2023-08-03 09:24 UTC, SammyOina commented on timescale/timescale.go
> +		queries = append(queries, "version = :version")
```suggestion
		queries = append(queries, "mf_version = :version")
```

2023-08-03 10:06 UTC, SammyOina commented on timescale/timescale.go
> +		queries = append(queries, "version = :version")
you also have to manually test your PRs before submission

2023-08-03 11:13 UTC, drasko approved these changes
LGTM

2023-08-03 11:13 UTC, merged