NOISSUE - Update client
mainflux/callhome pull request #4
Opened 2023-06-07 10:10 UTC by SammyOina

### What does this do?
Change logger level and update error messages

### Which issue(s) does this PR fix/relate to?
None

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes

2023-06-07 10:11 UTC, dborovcanin approved these changes

2023-06-08 10:54 UTC, drasko requested changes

2023-06-08 10:54 UTC, drasko commented on pkg/client/client.go
> +					hs.logger.Debug(fmt.Sprintf("failed to obtain service public IP address for sending Mainflux usage telemetry with error: %v", err))
Keep Warn() please, so that user is warned on failure

2023-06-08 11:55 UTC, drasko approved these changes
LGTM

2023-06-08 11:56 UTC, merged